name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every five minute
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - name: Commit & Push
        run: |
          git init
          git config user.name Zac10ck
          git config user.email iamabinabraham@gmail.com
      - uses: ervitis/github-profile-summary-cards@release
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

